name: Build and Deploy Snapshot
on:
  push:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  pull_request:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # As of Jackson 2.14 got Java 8 baseline so can build on later JDKs too
        java_version: ["8", "11", "17"]
        os: ["ubuntu-20.04"]
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    outputs:
      digest-8: ${{ steps.digests.outputs.digest-8 }}
      digest-11: ${{ steps.digests.outputs.digest-11 }}
      digest-17: ${{ steps.digests.outputs.digest-17 }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          cache: "maven"
          server-id: sonatype-nexus-snapshots
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          # See https://github.com/actions/setup-java/blob/v2/docs/advanced-usage.md#Publishing-using-Apache-Maven
          # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          # gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Build
        id: build
        run: |
          ./mvnw -B -q -ff -ntp verify
          mv ./target/jackson-core-2.14.0-SNAPSHOT.jar ./target/jackson-core-2.14.0-SNAPSHOT-${{ matrix.java_version }}.jar

          ARTIFACT_PATTERN=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout)-$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)*-${{ matrix.java_version }}.jar
          echo "artifact_pattern=$ARTIFACT_PATTERN" >> "$GITHUB_OUTPUT"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ./target
          name: "package-${{ matrix.java_version }}"
          if-no-files-found: warn
          retention-days: 1

      # digests must be generated from within ./target.
      # https://github.com/slsa-framework/slsa-github-generator/issues/1225
      - name: Generate subjects
        id: digests
        run: |
          DIGEST_NAME="digest-${{ matrix.java_version }}"
          touch "./$DIGEST_NAME"

          cd ./target
          echo "$DIGEST_NAME=$(sha256sum ${{ steps.build.outputs.artifact_pattern }} | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Save subject name
        uses: actions/upload-artifact@v3
        with:
          path: "digest-${{ matrix.java_version }}"
          name: digests
          if-no-files-found: warn

      # - name: Extract project Maven version
      #   id: projectVersion
      #   run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate -DforceStdout -Dexpression=project.version -q)" >>$GITHUB_OUTPUT
      # - name: Deploy snapshot
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
      #   env:
      #     CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      #     CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      #     # MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      #   run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
      # - name: Generate code coverage
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8'
      #   run: ./mvnw -B -q -ff -ntp test
      # - name: Publish code coverage
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8'
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./target/site/jacoco/jacoco.xml
      #     flags: unittests

  combine_digests:
    needs: [build]
    outputs:
      digests: ${{ steps.digests.outputs.digests }}
    runs-on: ubuntu-20.04
    env:
      DIGEST_8: "${{ needs.build.outputs.digest-8 }}"
      DIGEST_11: "${{ needs.build.outputs.digest-11 }}"
      DIGEST_17: "${{ needs.build.outputs.digest-17 }}"
    steps:
      - name: Combine digests
        id: digests
        run: |
          set -euo pipefail
          echo "$DIGEST_8" | base64 -d > digests.txt
          echo "$DIGEST_11" | base64 -d >> digests.txt
          echo "$DIGEST_17" | base64 -d >> digests.txt
          cat digests.txt
          echo "digests=$(cat digests.txt | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: get digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: ./digests

      - run: |
          ls ./digests > digest_names.txt
          cat digest_names.txt

  provenance:
    needs: [combine_digests]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.1
    with:
      base64-subjects: "${{ needs.combine_digests.outputs.digests }}"
      # Necessary until release of @v1.2.2
      # https://github.com/slsa-framework/slsa-github-generator/issues/1163
      compile-generator: true
      upload-assets: true # Optional: Upload to a new release
