name: Build and Deploy Snapshot
on:
  push:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  pull_request:
    branches:
      - master
      - "3.0"
      - "2.14"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # As of Jackson 2.14 got Java 8 baseline so can build on later JDKs too
        java_version: ["8", "11", "17"]
        os: ["ubuntu-20.04"]
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    outputs:
      hash-8: ${{ steps.hash.outputs.hash-8 }}
      hash-11: ${{ steps.hash.outputs.hash-11 }}
      hash-17: ${{ steps.hash.outputs.hash-17 }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          cache: "maven"
          server-id: sonatype-nexus-snapshots
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          # See https://github.com/actions/setup-java/blob/v2/docs/advanced-usage.md#Publishing-using-Apache-Maven
          # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          # gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Build
        id: build
        run: |
          ./mvnw -B -q -ff -ntp verify

          # hack to give the jars unique names so we can experiment with matrix strategies
          mv ./target/jackson-core-2.14.0-SNAPSHOT.jar \
            ./target/jackson-core-2.14.0-SNAPSHOT-${{ matrix.java_version }}.jar

          ARTIFACT_PATTERN=$( \
            ./mvnw help:evaluate \
              -Dexpression=project.artifactId -q -DforceStdout)-$( \
            ./mvnw help:evaluate \
              -Dexpression=project.version -q -DforceStdout)*-${{ matrix.java_version }}.jar
          echo "artifact_pattern=$ARTIFACT_PATTERN" >> "$GITHUB_OUTPUT"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ./target
          name: "package-${{ matrix.java_version }}"
          if-no-files-found: warn

      # Until generator_generic_slsa3@v1.2.3, calculate hashes from target
      # https://github.com/slsa-framework/slsa-github-generator/issues/1225
      - name: Generate subject
        id: hash
        run: |
          cd ./target

          echo "hash-${{ matrix.java_version }}=$( \
            sha256sum ${{ steps.build.outputs.artifact_pattern }} | \
            base64 -w0 \
          )" >> "$GITHUB_OUTPUT"

      # - name: Extract project Maven version
      #   id: projectVersion
      #   run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate -DforceStdout -Dexpression=project.version -q)" >>$GITHUB_OUTPUT
      # - name: Deploy snapshot
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
      #   env:
      #     CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      #     CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
      #     # MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      #   run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
      # - name: Generate code coverage
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8'
      #   run: ./mvnw -B -q -ff -ntp test
      # - name: Publish code coverage
      #   if: github.event_name != 'pull_request' && matrix.java_version == '8'
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./target/site/jacoco/jacoco.xml
      #     flags: unittests

  combine_hashes:
    needs: [build]
    runs-on: ubuntu-20.04
    outputs:
      hashes: ${{ steps.hashes.outputs.hashes }}
    env:
      HASHES: ${{ toJSON(needs.build.outputs) }}
    steps:
      - id: hashes
        run: |
          echo "$HASHES" | jq -r '.[] | @base64d' | sed "/^$/d" > hashes.txt
          echo "hashes=$(cat hashes.txt | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [combine_hashes]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.2
    with:
      base64-subjects: "${{ needs.combine_hashes.outputs.hashes }}"
      upload-assets: true # Optional: Upload to a new release
